### ISSUE TITLE
Using non default entity manager

### ISSUE THREAD

**Issue by ppounder** [FriendsOfSymfony/FOSMessageBundle#202]
Hi there,

I'm getting:

```
The class 'Acme\DemoBundle\Entity\Message' was not found in the chain configured namespaces 
```

I have everything installed as per documentation. FOSMessageBundle is in AppKernal etc, entities have correct namespaces. 

I believe this is because I'm using a non default entity manager.

I have the following in the config.yml

```
entity_managers:
    default:
        connection: default
    kp:
        connection: kp
        mappings:
            FOSUserBundle: ~
            FOSMessageBundle: ~
            AcmeDemoBundle: ~
```

What do I need to add to the fos_message config for this to work. In FOSUserBundle, I would use the model_manager_name: kp

Any thoughts?

Kind regards
Paul
