### ISSUE TITLE
cannot declare fos_message as a servi

### ISSUE THREAD

**Issue by Ritin** [FriendsOfSymfony/FOSMessageBundle#227]
Hi,
I want to overiride the NewThreadMessageFormType for
1. Removing the Subject (not required)
2 css Designing, ie customizing the Form to use form_row(form.recipient)
and not
{{ form_widget(form) }}

i am geting dependecy Errors
I have successfully custimzed the Profile + Edit Forms
but following the same steps for Message Bundle does not work
TIA
//---------------------------------------------------------------------ERRORS

```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
Unable to replace alias "conn_user_new_thread.new_thread_form.type" with             "fos_message.new_thread_form.type".

[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
The service definition "conn_user_new_thread.new_thread_form.type" does not exist.
```

//---------------------------------------------------------------------<br>

```
config.yml:
    fos_message:
        db_driver: orm
        thread_class: Conn\AaBundle\Entity\Thread
        message_class: Conn\AaBundle\Entity\Message
        new_thread_form:
            type: conn_user_new_thread.new_thread_form.type
            # handler: conn_user.form.handler.thread
            # handler: fos_message.new_thread_form.handler
            # model: FOS\MessageBundle\FormModel\NewThreadMessage
            model: Conn\AaBundle\FormModel\NewThreadMessage
            # validation_groups: [ConnThread]
```

//---------------------------------------------------------------------
services.yml:

```
conn_user_new_thread.new_thread_form.type:
    class: Conn\AaBundle\FormType\NewThreadMessageFormType
    # arguments: [%fos_message.thread_class%]
    tags:
        - { name: form.type, alias: conn_user_new_thread }
```

//-------------------------------------------------------------
    namespace Conn\AaBundle\FormType;

```
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use FOS\MessageBundle\FormType\NewThreadMessageFormType as mBaseType;

class NewThreadMessageFormType extends mBaseType{
.....
....
....
public function getName()
{
    return 'conn_user_new_thread';
}
```
