### ISSUE TITLE
Installation instructions is missing configuration step

### ISSUE THREAD

**Issue by umpirsky** [FriendsOfSymfony/FOSMessageBundle#247]
In https://github.com/FriendsOfSymfony/FOSMessageBundle/blob/master/Resources/doc/01-installation.md  configuration step is required, but is missing.

Minimal required configuration for this bundle is:

```
fos_message:
    db_driver: orm
    thread_class: Acme\MessageBundle\Entity\Thread
    message_class: Acme\MessageBundle\Entity\Message
```
