### ISSUE TITLE
Can not override  NewThreadMessageFormType

### ISSUE THREAD

**Issue by rimouesleti** [FriendsOfSymfony/FOSMessageBundle#252]
Hi, I want to override NewThreadMessageForm to : add bootstrap classes to the form inputs and change the receiver text input to a select list (user entity list)

I already did this with fosUserBundle but with messageBundle i get this error : 
```
The required option "class" is missing.
```

**************config.yml*************************
```
imports:
  ...
    - { resource: @MessageBundle/Resources/config/services.yml }

fos_message:
    db_driver: orm
    thread_class: ICGM2\MessageBundle\Entity\Thread
    message_class: ICGM2\MessageBundle\Entity\Message
    new_thread_form:
        type: icgm2_new_thread.new_thread_form.type
```

*****************services.yml**********************************
```
  services:
  icgm2_new_thread.new_thread_form.type:
        class: ICGM2\MessageBundle\FormType\NewThreadMessageFormType
        arguments: [%fos_message.thread_class%]
        tags:
            - { name: form.type, alias: icgm2_new_thread}
```

*************NewThreadMessageFormType.php******************
```
namespace ICGM2\MessageBundle\FormType;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use FOS\MessageBundle\FormType\NewThreadMessageFormType as BaseType;

class NewThreadMessageFormType extends BaseType{
.....
    public function getName()
    {
        return 'icgm2_new_thread';
    }
}
```
************************************************************************************
