### ISSUE TITLE
Get recipient by query

### ISSUE THREAD

**Issue by Xyr2** [FriendsOfSymfony/FOSMessageBundle#261]
Hey there, 
I want to make links on my userprofiles to send a message to this user, and I thought it would be the best way to pass the recipients like this ` /messages/new?recipient=lukas ` and use it as an initial text in the recipient form field.
Any idea how I can achieve this? Couldn't find anything related here or at StackOverflow. Thanks for your help! :)

**Comment by tgalopin** [comment]
You have to implement your own version of the NewThreadFormFactory. A form factory is a service able to create form instances, so by redefining your own for the new thread, you will be able to prefill fields as you want.

Base your custom NewThreadFormFactory on the default one (https://github.com/FriendsOfSymfony/FOSMessageBundle/blob/master/FormFactory/NewThreadMessageFormFactory.php) and register it as a service. You can pass the request and the Doctrine manager to it as dependencies in order to create a prefilled message with the user in the URL. Once declared, use the config key `new_thread_form.factory` to use your service as the factory so when the bundle controller will call it, it will do what you want.

If you need more help, I can give a hand.

**Comment by Xyr2** [comment]
Hey, thanks for your fast reply! :)

Okay, first I wanted to check if my custom form factory service is working, but failed at this very first step.. here is what it did:

```
<?php

// src/AppBundle/MessageBundle/FormFactory/NewThreadFormFactory.php

namespace AppBundle\MessageBundle\FormFactory;

use FOS\MessageBundle\FormFactory\NewThreadMessageFormFactory as BaseFactory;

class NewThreadMessageFormFactory extends BaseFactory
{
	/**
	* Creates a new thread message
	*
	* @return Form
	*/
	public function create() {

		$message = $this->createModelInstance();
		return $this->formFactory->createNamed($this->formName, $this->formType, $message);

	}
}
```
config.yml
```
fos_message:
    db_driver: orm
    thread_class: AppBundle\MessageBundle\Entity\Thread
    message_class: AppBundle\MessageBundle\Entity\Message
    new_thread_form:
              factory: app_new_thread.new_thread_form.factory
```

services.yml
```
    app_new_thread.new_thread_form.factory:
        class: AppBundle\MessageBundle\FormFactory\NewThreadMessageFormFactory
        arguments: [%fos_message.thread_class%]
        tags:
        - { name: form.factory, alias: app_new_thread }
```

Now I'm getting this error:
```
Attempted to load class "NewThreadMessageFormFactory" from namespace "AppBundle\MessageBundle\FormFactory".
Did you forget a "use" statement for "FOS\MessageBundle\FormFactory\NewThreadMessageFormFactory"?
```


And to be honest, I have no idea where to pass the username to the form field in the FormFactory. I learned to fetch a query on a controller like this: 
```
    public function indexAction(Request $request) {
        $recipient = $request->query->get('recipient');
```

and would pass it to a text form like this:
```
$builder->add('recipient', 'text', array(
    'data' => $recipient,
));
```

So if you could give me a hint, that would be awesom.. :)

Greetings Raphael

**Comment by tgalopin** [comment]
Your first problem seems to be a typo in the filename or something like that. The autoloader can't find your service class, are you sure everything is fine with the file / class / namespace names?

For your second problem, what I would personnaly do is pass the request (and the entity manager) as a parameter to your custom factory (either by adding the service to the `request` scope or by passing the whole container to it). Your factory would then look like something like:

``` php
<?php

// src/AppBundle/MessageBundle/FormFactory/NewThreadFormFactory.php

namespace AppBundle\MessageBundle\FormFactory;

use FOS\MessageBundle\FormFactory\NewThreadMessageFormFactory as BaseFactory;

class NewThreadMessageFormFactory extends BaseFactory
{
	protected $request;
	protected $em;

	public function __construct($request, $em)
	{
		$this->request = $request;
		$this->em = $em;
	}

    /**
    * Creates a new thread message
    *
    * @return Form
    */
    public function create() {

        $message = $this->createModelInstance();

        // Here you can edit the default message using the request from $this->request
        // and the entity manager from $this->em
        // If you find a user using the request and the em, you include it into the message:
        $message->setSender($user);

        return $this->formFactory->createNamed($this->formName, $this->formType, $message);

    }
}
```

I didn't try the code, but it's the idea that matters.

**Comment by Xyr2** [comment]
Hey, thank you for that, but I couldn't try your code yet, because I can't manage to get rid of the "Attempted to load class" error. I can't see any typos or wrong file structures, could you please have a second look for me? :)

**Comment by tgalopin** [comment]
I reviewed the code, all seems fine from what I have. But it can be more complex than just typos. I noticed some identations problems in the yml files you provided, perhaps it's it. I can't help more here.

**Comment by Xyr2** [comment]
Okay I got it now, thanks for your hint, it helped me a lot achieving this.. :)

in my Services.yml I did this:
```yaml
    app_new_thread.new_thread_form.factory:
        class: AppBundle\MessageBundle\FormFactory\NewThreadMessageFormFactory
        public: false
        scope: request
        arguments:
            - @doctrine.orm.entity_manager
            - @request
            - @form.factory
            - @fos_message.new_thread_form.type
            - %fos_message.new_thread_form.name%
            - %fos_message.new_thread_form.model%
```

and in my FormFactory this:

```php
<?php

// src/AppBundle/MessageBundle/FormFactory/NewThreadFormFactory.php

namespace AppBundle\MessageBundle\FormFactory;

use FOS\MessageBundle\FormFactory\NewThreadMessageFormFactory as BaseFactory;
use Doctrine\ORM\EntityManager;
use Symfony\Component\HttpFoundation\Request;

class NewThreadMessageFormFactory extends BaseFactory
{

    protected $entityManager;
    protected $request;

    public function __construct(EntityManager $entityManager, Request $request, $formFactory, $formType, $formName, $messageClass)
    {
        parent::__construct($formFactory, $formType, $formName, $messageClass);

        $this->entityManager = $entityManager;
        $this->request = $request;
    }

    /**
     * Creates a new thread message
     *
     * @return Form
     */
    public function create()
    {
        $message = $this->createModelInstance();

        $username = $this->request->query->get('user');
        $user = $this->entityManager->getRepository('AppBundle:User')
                ->findOneBy(array('username' => $username));

        $message->setRecipient($user);

        return $this->formFactory->createNamed($this->formName, $this->formType, $message);
    }
}
```
