### ISSUE TITLE
Issue with JMSSerializerBundle

### ISSUE THREAD

**Issue by marvA101** [FriendsOfSymfony/FOSMessageBundle#270]
Hello everyone,

I'm using the bundle in combinaison with JMS Serializer and FOSRestBundle to create a small API.
I'm trying to select which fields of the Message and Thread entities are serialized.
For some reason, my config files are totally ignored for those two entities only. I tried using annotations and separate YAML file but nothing works.

Any idea on what could be the problem?
Thanks

```
#/app/serializer/CoreBundle/Entity.Message.yml
MyVendor\CoreBundle\Entity\Message:
    exclusion_policy: ALL
    properties :
        sender :
            expose : false
            exclude : true
        thread :
            expose : false
            exclude : true
```

```
#/app/serializer/FOSMessageBundle/Model.Message.yml
FOS\MessageBundle\Model\Message:
    exclusion_policy: ALL
    properties :
        sender:
            expose : false
            exclude : true
```

**Comment by marvA101** [comment]
Nevermind, I forgot to specify the metadata files path in `config.yml`

```
jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSMessageBundle:
                namespace_prefix: "FOS\\MessageBundle"
                path: "%kernel.root_dir%/serializer/FOSMessageBundle"
```
