### ISSUE TITLE
Is it possible to use a ChoiceType instead of a TextType for recipients ?

### ISSUE THREAD

**Issue by charafsalmi** [FriendsOfSymfony/FOSMessageBundle#297]
I am struggling trying to use a Select Input Field to display a Select2 widget instead of the Text Input Field.

I add new services in `services.yml` : 
```
  app.type.recipients_selector:
    class: AppBundle\Form\Type\RecipientsType
    arguments: ['@app.type.recipients_data_transformer']
    tags:
        - { name: form.type }
  app.type.recipients_data_transformer:
    class: AppBundle\DataTransformer\RecipientsDataTransformer
    arguments: ['@app.type.user_to_username_transformer']
  app.type.user_to_username_transformer:
    class: AppBundle\DataTransformer\UserToUsernameTransformer
    arguments: ['@fos_user.user_manager']
```

And config.xml
```
fos_message:
    db_driver: orm
    thread_class: AppBundle\Entity\Thread
    message_class: AppBundle\Entity\Message
    new_thread_form:
      type:               AppBundle\Form\Type\NewThreadMultipleMessageFormType
      handler:            fos_message.new_thread_multiple_form.handler
      model:              AppBundle\Form\Model\NewThreadMultipleMessage
      name:               message
```

Then, I dupplicated these services' files in the right places. 

I also created a JSON Controller to give back the filtered list of users ID I want my Select2 to display.

But when I try to send a message to the right user, it says that this user doesn't exist.

I can not figure out how the data transformers handle the information in this case.

The `RecipientsDataTransformer->transform` method allows get an empty array as a parameter. How is that possible when the select input field returns an ID ?

What can I do more ? 

Thank you.
