### ISSUE TITLE
Circular Dependency with fos_user

### ISSUE THREAD

**Issue by haterecoil** [FriendsOfSymfony/FOSMessageBundle#306]
Hello,

First time trying this bundle which seemed pretty great (even though no commits since a while).

However I have quite a problem, and I am not a pro of circularreferences :S 

```
Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException: 

Circular reference detected for service "doctrine.orm.default_entity_manager", path: 

"doctrine.orm.default_entity_manager -> doctrine.dbal.default_connection -> fos_user.mailer -> templating -> twig -> fos_message.twig_extension -> fos_message.provider -> fos_message.thread_manager". in /fullpath/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php on line 299
```

I am using (amongst other things) :
- "friendsofsymfony/user-bundle": "~2.0",
- "friendsofsymfony/message-bundle": "^1.3",
- "symfony/symfony": "~3.3.5",

and PHP 7.0

Basically, I just installed the bundled, followed instructions, and setup my config.yml like that : 

```yaml
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: MyProject\AppBundle\Entity\User
    from_email:
        address: "%mailer_admin%"
        sender_name: "%mailer_user%"
    resetting:
        email:
            template:   :emails:password_resetting.email.twig

fos_message:
  thread_class: MyProject\AppBundle\Entity\Thread
  message_class: MyProject\AppBundle\Entity\Message
  db_driver: orm
```

Do you have any idea of what I could do ? I'm pretty sure it is something easy but I really don't find my say since several hours...

Thanks if someone is stoping by and can give me an advice (or a solution !? :D )

Cheers,
