### ISSUE TITLE
multiple recipients exists but isn't referenced in the documentation

### ISSUE THREAD

**Issue by hex333ham** [FriendsOfSymfony/FOSMessageBundle#333]
it can actually be enabled by adding the following to the `fos_message` config in `services.yaml`:

```yaml
    new_thread_form:
      type:               FOS\MessageBundle\FormType\NewThreadMultipleMessageFormType
      handler:            fos_message.new_thread_multiple_form.handler
      model:              FOS\MessageBundle\FormModel\NewThreadMultipleMessage
      name: message
```

looks experimental, needs revisiting at some point
